server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        
        # Esta es la línea mágica que soluciona tu problema:
        # Intenta buscar el archivo, si no lo encuentra busca un directorio, 
        # y si no encuentra nada, envía la petición al index.html
        try_files $uri $uri/ /index.html;
    }

    # Redirección de errores del servidor
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}